import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../ViewModel/auth_viewmodel.dart';
import '../model/API/product_repository.dart';
import '../model/producto.dart';

class RegistrarProductoPage extends StatefulWidget {
  final Producto? producto; // Optional product for editing

  const RegistrarProductoPage({super.key, this.producto});

  @override
  State<RegistrarProductoPage> createState() => _RegistrarProductoPageState();
}

class _RegistrarProductoPageState extends State<RegistrarProductoPage> {
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();
  final _descriptionCtrl = TextEditingController();
  final _brandCtrl = TextEditingController();
  final _priceCtrl = TextEditingController();
  final _stockCtrl = TextEditingController();
  final _netContentCtrl = TextEditingController();
  final _imageUrlCtrl = TextEditingController();

  // Unit Dropdown
  final List<String> _units = ['g', 'ml', 'l', 'kg', 'mg', 'units'];
  String? _selectedUnit;

  bool _loading = false;
  bool _isAutoGeneratedImage = false;
  bool get _isEditing => widget.producto != null;

  final _repo = ProductRepository();

  @override
  void initState() {
    super.initState();
    _nameCtrl.addListener(_onNameChanged);

    // Pre-fill if editing
    if (_isEditing) {
      final p = widget.producto!;
      _nameCtrl.text = p.nombre;
      _priceCtrl.text = p.precio.toString();
      _imageUrlCtrl.text = p.imagen;

      // TODO: If Producto model has brand/description/etc, pre-fill them too.
      // Currently Producto model (from catalogo.dart view snippets) only has:
      // id, nombre, precio, imagen.
      // If the model is updated to have more fields, use them here.
      // For now, these might be empty if not in the model.

      // Since Producto is minimal in frontend for now, we can only edit
      // what we have or need to fetch full details first.
      // Assuming for now user re-enters or we just support price/name updates
      // until `Producto` model is expanded.
    }
  }

  @override
  void dispose() {
    _nameCtrl.removeListener(_onNameChanged);
    _nameCtrl.dispose();
    _descriptionCtrl.dispose();
    _brandCtrl.dispose();
    _priceCtrl.dispose();
    _stockCtrl.dispose();
    _netContentCtrl.dispose();
    _imageUrlCtrl.dispose();
    super.dispose();
  }

  void _onNameChanged() {
    // Only auto-search if field was empty or previously auto-generated
    if (_nameCtrl.text.trim().isNotEmpty) {
      // Debounce logic could go here, but for now we rely on explicit button press
      // or just keep manual trigger to save API calls/performance?
      // The user request said "al darle en el boton... buscar".
      // So we keep the button logic as primary.
      // The existing listener logic was:
      // if (_imageUrlCtrl.text.isEmpty || _isAutoGeneratedImage) { _generateImageUrl(); }
      // Since this is now an async API call, let's NOT do it automatically on every keystroke.
      // We'll rely on the user clicking the button for the REAL search.
    }
  }

  Future<void> _generateImageUrl() async {
    final name = _nameCtrl.text.trim();
    if (name.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Ingrese un nombre para buscar imagen')),
      );
      return;
    }

    setState(() => _loading = true); // Reuse loading or add specific one

    // Parse numeric content if available
    double? netContent;
    if (_netContentCtrl.text.trim().isNotEmpty) {
      netContent = double.tryParse(_netContentCtrl.text.replaceAll(',', '.'));
    }

    final imageUrl = await _repo.searchProductImage(
      name: name,
      brand: _brandCtrl.text.trim().isEmpty ? null : _brandCtrl.text.trim(),
      netContent: netContent,
      netContentUnit: _selectedUnit,
    );

    if (mounted) {
      setState(() {
        _loading = false;
        if (imageUrl != null && imageUrl.isNotEmpty) {
          _imageUrlCtrl.text = imageUrl;
          _isAutoGeneratedImage = true;
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('No se encontró imagen')),
          );
        }
      });
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _loading = true);

    double? price;
    if (_priceCtrl.text.trim().isNotEmpty) {
      price = double.tryParse(_priceCtrl.text.replaceAll(',', '.'));
    }

    double? netContent;
    if (_netContentCtrl.text.trim().isNotEmpty) {
      netContent = double.tryParse(_netContentCtrl.text.replaceAll(',', '.'));
    }

    int? stock;
    if (_stockCtrl.text.trim().isNotEmpty) {
      stock = int.tryParse(_stockCtrl.text.trim());
    }

    final auth = context.read<AuthViewModel>();
    final token = auth.token;

    if (token == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Error: No estás autenticado')),
      );
      setState(() => _loading = false);
      return;
    }

    try {
      if (_isEditing) {
        await _repo.updateProduct(
          token: token,
          id: widget.producto!.id,
          name: _nameCtrl.text.trim(),
          brand: _brandCtrl.text.trim().isEmpty ? null : _brandCtrl.text.trim(),
          description: _descriptionCtrl.text.trim().isEmpty
              ? null
              : _descriptionCtrl.text.trim(),
          price: price,
          stock: stock,
          netContent: netContent,
          netContentUnit: _selectedUnit,
          imageUrl: _imageUrlCtrl.text.trim().isEmpty
              ? null
              : _imageUrlCtrl.text.trim(),
        );
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Producto actualizado exitosamente')),
          );
          Navigator.pop(context);
        }
      } else {
        await _repo.createProduct(
          token: token,
          name: _nameCtrl.text.trim(),
          brand: _brandCtrl.text.trim().isEmpty ? null : _brandCtrl.text.trim(),
          description: _descriptionCtrl.text.trim().isEmpty
              ? null
              : _descriptionCtrl.text.trim(),
          price: price,
          stock: stock,
          netContent: netContent,
          netContentUnit: _selectedUnit,
          imageUrl: _imageUrlCtrl.text.trim().isEmpty
              ? null
              : _imageUrlCtrl.text.trim(),
        );

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Producto creado exitosamente')),
          );
          Navigator.pop(context);
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_isEditing ? 'Editar Producto' : 'Registrar Producto'),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            key: _formKey,
            child: SingleChildScrollView(
              child: Column(
                children: [
                  TextFormField(
                    controller: _nameCtrl,
                    decoration: const InputDecoration(labelText: 'Nombre *'),
                    validator: (v) => (v == null || v.trim().isEmpty)
                        ? 'Ingrese un nombre'
                        : null,
                  ),
                  const SizedBox(height: 12),
                  TextFormField(
                    controller: _descriptionCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Descripción',
                      border: OutlineInputBorder(),
                    ),
                    maxLines: 2,
                  ),
                  const SizedBox(height: 12),
                  TextFormField(
                    controller: _brandCtrl,
                    decoration: const InputDecoration(labelText: 'Marca'),
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: _priceCtrl,
                          keyboardType: const TextInputType.numberWithOptions(
                            decimal: true,
                          ),
                          decoration: const InputDecoration(
                            labelText: 'Precio *',
                            prefixText: '\$ ',
                          ),
                          validator: (v) {
                            if (v == null || v.isEmpty) return 'Requerido';
                            if (double.tryParse(v.replaceAll(',', '.')) ==
                                null) {
                              return 'Inválido';
                            }
                            return null;
                          },
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: TextFormField(
                          controller: _stockCtrl,
                          keyboardType: TextInputType.number,
                          decoration: const InputDecoration(labelText: 'Stock'),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      Expanded(
                        flex: 2,
                        child: TextFormField(
                          controller: _netContentCtrl,
                          keyboardType: const TextInputType.numberWithOptions(
                            decimal: true,
                          ),
                          decoration: const InputDecoration(
                            labelText: 'Contenido Neta *',
                          ),
                          validator: (v) {
                            if (v == null || v.isEmpty) return 'Requerido';
                            if (double.tryParse(v.replaceAll(',', '.')) ==
                                null) {
                              return 'Inválido';
                            }
                            return null;
                          },
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        flex: 1,
                        child: DropdownButtonFormField<String>(
                          value: _selectedUnit,
                          decoration: const InputDecoration(
                            labelText: 'Unidad *',
                          ),
                          items: _units.map((unit) {
                            return DropdownMenuItem(
                              value: unit,
                              child: Text(unit),
                            );
                          }).toList(),
                          onChanged: (val) =>
                              setState(() => _selectedUnit = val),
                          validator: (v) => v == null ? 'Requerido' : null,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: _imageUrlCtrl,
                          decoration: const InputDecoration(
                            labelText: 'URL imagen',
                            hintText: 'https://...',
                          ),
                          onChanged: (value) {
                            if (value.isNotEmpty) {
                              setState(() => _isAutoGeneratedImage = false);
                            }
                          },
                        ),
                      ),
                      IconButton(
                        onPressed: _generateImageUrl,
                        tooltip: 'Autogenerar imagen',
                        icon: const Icon(Icons.auto_fix_high),
                      ),
                    ],
                  ),
                  const SizedBox(height: 20),
                  if (_imageUrlCtrl.text.isNotEmpty)
                    Padding(
                      padding: const EdgeInsets.only(bottom: 20),
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(8),
                        child: Image.network(
                          _imageUrlCtrl.text,
                          height: 150,
                          fit: BoxFit.cover,
                          errorBuilder: (context, error, stackTrace) =>
                              const Text('No se pudo cargar la imagen'),
                        ),
                      ),
                    ),
                  SizedBox(
                    width: double.infinity,
                    height: 50,
                    child: ElevatedButton(
                      onPressed: _loading ? null : _submit,
                      child: _loading
                          ? const CircularProgressIndicator()
                          : const Text('Registrar Producto'),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
